const page=document.body.dataset.page;
const nav=[['introduce','소개'],['article','기사'],['image','이미지'],['video','영상'],['final','Final project']];
document.querySelector('#site-header').innerHTML='<div class="topline"><div class="wrap"><span>한국경제 AI 교육 · 학습과 실험의 기록</span><span>LEARN. CREATE. ARCHIVE.</span></div></div><header class="header"><div class="wrap"><a class="brand" href="article.html"><span class="brand-icon">Ai</span><span><strong>한경 AI 아카이브</strong><small>HANKYUNG AI PORTFOLIO</small></span></a><nav aria-label="주 메뉴">'+nav.map(([id,label])=>'<a href="'+id+'.html" '+(page===id?'class="active" aria-current="page"':'')+'>'+label+'</a>').join('')+'</nav><span class="owner">나의 크리에이티브 노트</span></div></header>';
document.querySelector('#site-footer').innerHTML='<footer class="footer"><div class="wrap"><div><strong>한경 AI 아카이브</strong><p>한국경제 AI 교육에서 배우고, 만들고, 발견한 것들.</p><small>개인 학습 포트폴리오 · 교육기관 공식 사이트가 아닙니다.</small></div><div><p>© 2026 AI Portfolio. All rights reserved.</p><small>현재 콘텐츠는 구성 확인을 위한 예시입니다.<br>참고 사진: Unsplash · Minku Kang, Conny Schneider, Gaétan Meyer</small></div></div></footer>';
const dialog=document.querySelector('dialog');
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#dialog-content').innerHTML=document.getElementById(b.dataset.open).innerHTML;dialog.showModal();}));
document.querySelector('[data-close]').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});let count=0;document.querySelectorAll('[data-category]').forEach(x=>{x.hidden=b.dataset.filter!=='all'&&x.dataset.category!==b.dataset.filter;if(!x.hidden)count++;});const c=document.querySelector('#count');if(c)c.textContent=String(count).padStart(2,'0');}));
